version: '3.8'

services:
  app:
    build: .
    
    ports:
      - "8080:80"
      
    volumes:
      - .:/var/www/html
      
    command: >
      bash -c "chmod -R 777 /var/www/html/database &&
               apache2-foreground"